using GeneratorGame.Data;
using Microsoft.EntityFrameworkCore;

namespace GeneratorGame.Services;

public static class AchievementDatabaseInitializer
{
    public static async Task EnsureSchemaAsync(AppDbContext db)
    {
        if (!db.Database.IsNpgsql())
        {
            return;
        }

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "UserStats" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UserId" integer NOT NULL,
                "GamesPlayed" integer NOT NULL DEFAULT 0,
                "Wins" integer NOT NULL DEFAULT 0,
                "TotalPlayTimeMs" bigint NOT NULL DEFAULT 0,
                "Experience" integer NOT NULL DEFAULT 0,
                "Level" integer NOT NULL DEFAULT 1,
                "FavoriteGenerator" text NOT NULL DEFAULT 'bitebynight',
                "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                CONSTRAINT "FK_UserStats_Users_UserId"
                    FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS "UserAchievements" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UserId" integer NOT NULL,
                "Key" text NOT NULL,
                "Title" text NOT NULL,
                "Description" text NOT NULL,
                "Icon" text NOT NULL DEFAULT '★',
                "Experience" integer NOT NULL DEFAULT 0,
                "UnlockedAt" timestamp with time zone NOT NULL DEFAULT now(),
                CONSTRAINT "FK_UserAchievements_Users_UserId"
                    FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
            );

            ALTER TABLE "UserStats" ADD COLUMN IF NOT EXISTS "GamesPlayed" integer NOT NULL DEFAULT 0;
            ALTER TABLE "UserStats" ADD COLUMN IF NOT EXISTS "Wins" integer NOT NULL DEFAULT 0;
            ALTER TABLE "UserStats" ADD COLUMN IF NOT EXISTS "TotalPlayTimeMs" bigint NOT NULL DEFAULT 0;
            ALTER TABLE "UserStats" ADD COLUMN IF NOT EXISTS "Experience" integer NOT NULL DEFAULT 0;
            ALTER TABLE "UserStats" ADD COLUMN IF NOT EXISTS "Level" integer NOT NULL DEFAULT 1;
            ALTER TABLE "UserStats" ADD COLUMN IF NOT EXISTS "FavoriteGenerator" text NOT NULL DEFAULT 'bitebynight';
            ALTER TABLE "UserStats" ADD COLUMN IF NOT EXISTS "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now();

            ALTER TABLE "UserAchievements" ADD COLUMN IF NOT EXISTS "Key" text NOT NULL DEFAULT '';
            ALTER TABLE "UserAchievements" ADD COLUMN IF NOT EXISTS "Title" text NOT NULL DEFAULT '';
            ALTER TABLE "UserAchievements" ADD COLUMN IF NOT EXISTS "Description" text NOT NULL DEFAULT '';
            ALTER TABLE "UserAchievements" ADD COLUMN IF NOT EXISTS "Icon" text NOT NULL DEFAULT '★';
            ALTER TABLE "UserAchievements" ADD COLUMN IF NOT EXISTS "Experience" integer NOT NULL DEFAULT 0;
            ALTER TABLE "UserAchievements" ADD COLUMN IF NOT EXISTS "UnlockedAt" timestamp with time zone NOT NULL DEFAULT now();

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_UserStats_UserId"
                ON "UserStats" ("UserId");

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_UserAchievements_UserId_Key"
                ON "UserAchievements" ("UserId", "Key");

            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'UserAchievements'
                      AND column_name = 'Id'
                      AND column_default IS NULL
                ) THEN
                    CREATE SEQUENCE IF NOT EXISTS "UserAchievements_Id_seq";
                    ALTER SEQUENCE "UserAchievements_Id_seq" OWNED BY "UserAchievements"."Id";
                    ALTER TABLE "UserAchievements"
                    ALTER COLUMN "Id" SET DEFAULT nextval('"UserAchievements_Id_seq"'::regclass);
                    PERFORM setval(
                        '"UserAchievements_Id_seq"'::regclass,
                        GREATEST(COALESCE((SELECT MAX("Id") FROM "UserAchievements"), 0), 1),
                        true
                    );
                END IF;

                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'UserStats'
                      AND column_name = 'Id'
                      AND column_default IS NULL
                ) THEN
                    CREATE SEQUENCE IF NOT EXISTS "UserStats_Id_seq";
                    ALTER SEQUENCE "UserStats_Id_seq" OWNED BY "UserStats"."Id";
                    ALTER TABLE "UserStats"
                    ALTER COLUMN "Id" SET DEFAULT nextval('"UserStats_Id_seq"'::regclass);
                    PERFORM setval(
                        '"UserStats_Id_seq"'::regclass,
                        GREATEST(COALESCE((SELECT MAX("Id") FROM "UserStats"), 0), 1),
                        true
                    );
                END IF;

                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'UserStats'
                      AND column_name = 'UpdatedAt'
                      AND data_type = 'text'
                ) THEN
                    ALTER TABLE "UserStats"
                    ALTER COLUMN "UpdatedAt" TYPE timestamp with time zone
                    USING COALESCE(NULLIF("UpdatedAt", '')::timestamp with time zone, now());
                END IF;

                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'UserAchievements'
                      AND column_name = 'UnlockedAt'
                      AND data_type = 'text'
                ) THEN
                    ALTER TABLE "UserAchievements"
                    ALTER COLUMN "UnlockedAt" TYPE timestamp with time zone
                    USING COALESCE(NULLIF("UnlockedAt", '')::timestamp with time zone, now());
                END IF;
            END $$;
            """);
    }

    public static async Task BackfillAllAsync(AppDbContext db, AchievementService achievements)
    {
        var userIds = await db.Scores
            .Select(s => s.UserId)
            .Distinct()
            .ToListAsync();

        foreach (var userId in userIds)
        {
            try
            {
                await achievements.BackfillAsync(userId);
                await db.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"ACHIEVEMENT NEON BACKFILL WARNING user {userId}: {ex.GetType().Name}: {ex.Message}");
                db.ChangeTracker.Clear();
            }
        }
    }
}
