using GeneratorGame.Data;
using GeneratorGame.Data.Models;
using Microsoft.EntityFrameworkCore;

namespace GeneratorGame.Services;

public class DailyRewardService
{
    private readonly AppDbContext _db;

    public DailyRewardService(AppDbContext db)
    {
        _db = db;
    }

    public static readonly DailyRewardDefinition[] Rewards =
    [
        new(1, "25 Diamons", "25 Diamons", 25, null),
        new(2, "50 Diamons", "50 Diamons", 50, null),
        new(3, "Переливающийся ник", "Уникальный цвет ника", 0, "rainbow_name"),
        new(4, "50 Diamons", "50 Diamons", 50, null),
        new(5, "50 Diamons", "50 Diamons", 50, null),
        new(6, "50 Diamons", "50 Diamons", 50, null),
        new(7, "Диамант возле ника", "Уникальный emoji возле ника", 0, "diamond_emoji")
    ];

    public async Task<DailyRewardView> GetViewAsync(int userId)
    {
        var state = await GetOrCreateStateAsync(userId);
        var stat = await GetOrCreateStatAsync(userId);
        await _db.SaveChangesAsync();
        return BuildView(state, stat, false, null);
    }

    public async Task<DailyRewardView> ClaimAsync(int userId)
    {
        var state = await GetOrCreateStateAsync(userId);
        var stat = await GetOrCreateStatAsync(userId);
        if (!CanClaim(state))
        {
            return BuildView(state, stat, false, "Сегодняшний подарок уже забран");
        }

        var reward = Rewards.First(r => r.Day == state.CurrentDay);
        if (reward.Diamons > 0)
        {
            var multiplier = await GetDiamonsMultiplierAsync(userId);
            stat.Diamons += reward.Diamons * multiplier;
        }
        if (reward.Cosmetic == "rainbow_name")
        {
            stat.RainbowNameUnlocked = true;
            stat.RainbowNameEnabled = true;
        }
        if (reward.Cosmetic == "diamond_emoji")
        {
            stat.DiamondEmojiUnlocked = true;
            stat.DiamondEmojiEnabled = true;
        }

        state.LastClaimedAt = DateTime.UtcNow;
        state.CurrentDay = state.CurrentDay >= 7 ? 1 : state.CurrentDay + 1;
        if (state.CurrentDay == 1) state.CycleStartedAt = DateTime.UtcNow;
        stat.UpdatedAt = DateTime.UtcNow;
        await _db.SaveChangesAsync();

        return BuildView(state, stat, true, $"Получено: {reward.Title}");
    }

    public async Task EnsureSchemaAsync()
    {
        if (_db.Database.IsNpgsql())
        {
            await _db.Database.ExecuteSqlRawAsync("""
                ALTER TABLE "UserStats" ADD COLUMN IF NOT EXISTS "Diamons" integer NOT NULL DEFAULT 0;
                ALTER TABLE "UserStats" ADD COLUMN IF NOT EXISTS "RainbowNameUnlocked" boolean NOT NULL DEFAULT false;
                ALTER TABLE "UserStats" ADD COLUMN IF NOT EXISTS "RainbowNameEnabled" boolean NOT NULL DEFAULT false;
                ALTER TABLE "UserStats" ADD COLUMN IF NOT EXISTS "DiamondEmojiUnlocked" boolean NOT NULL DEFAULT false;
                ALTER TABLE "UserStats" ADD COLUMN IF NOT EXISTS "DiamondEmojiEnabled" boolean NOT NULL DEFAULT false;

                CREATE TABLE IF NOT EXISTS "DailyRewards" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "UserId" integer NOT NULL,
                    "CurrentDay" integer NOT NULL DEFAULT 1,
                    "LastClaimedAt" timestamp with time zone NULL,
                    "CycleStartedAt" timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT "FK_DailyRewards_Users_UserId"
                        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_DailyRewards_UserId"
                    ON "DailyRewards" ("UserId");
                """);
            return;
        }

        await AddSqliteColumn("UserStats", "Diamons", "INTEGER NOT NULL DEFAULT 0");
        await AddSqliteColumn("UserStats", "RainbowNameUnlocked", "INTEGER NOT NULL DEFAULT 0");
        await AddSqliteColumn("UserStats", "RainbowNameEnabled", "INTEGER NOT NULL DEFAULT 0");
        await AddSqliteColumn("UserStats", "DiamondEmojiUnlocked", "INTEGER NOT NULL DEFAULT 0");
        await AddSqliteColumn("UserStats", "DiamondEmojiEnabled", "INTEGER NOT NULL DEFAULT 0");
        await _db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "DailyRewards" (
                "Id" INTEGER NOT NULL CONSTRAINT "PK_DailyRewards" PRIMARY KEY AUTOINCREMENT,
                "UserId" INTEGER NOT NULL,
                "CurrentDay" INTEGER NOT NULL DEFAULT 1,
                "LastClaimedAt" TEXT NULL,
                "CycleStartedAt" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT "FK_DailyRewards_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_DailyRewards_UserId" ON "DailyRewards" ("UserId");
            """);
    }

    private async Task AddSqliteColumn(string table, string column, string definition)
    {
        var connection = _db.Database.GetDbConnection();
        var shouldClose = connection.State == System.Data.ConnectionState.Closed;
        if (shouldClose) await connection.OpenAsync();
        try
        {
            await using var cmd = connection.CreateCommand();
            cmd.CommandText = $"PRAGMA table_info(\"{table}\");";
            await using var reader = await cmd.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                if (string.Equals(reader.GetString(1), column, StringComparison.OrdinalIgnoreCase)) return;
            }
        }
        finally
        {
            if (shouldClose) await connection.CloseAsync();
        }

        var sql = $"""ALTER TABLE "{table}" ADD COLUMN "{column}" {definition};""";
        await _db.Database.ExecuteSqlRawAsync(sql);
    }

    private async Task<DailyRewardState> GetOrCreateStateAsync(int userId)
    {
        var state = await _db.DailyRewards.FirstOrDefaultAsync(r => r.UserId == userId);
        if (state != null) return state;

        state = new DailyRewardState { UserId = userId, CurrentDay = 1, CycleStartedAt = DateTime.UtcNow };
        _db.DailyRewards.Add(state);
        return state;
    }

    private async Task<UserStat> GetOrCreateStatAsync(int userId)
    {
        var stat = await _db.UserStats.FirstOrDefaultAsync(s => s.UserId == userId);
        if (stat != null) return stat;

        stat = new UserStat { UserId = userId, Level = 1 };
        _db.UserStats.Add(stat);
        return stat;
    }

    private async Task<int> GetDiamonsMultiplierAsync(int userId)
    {
        var vipUntil = await _db.Users
            .Where(u => u.Id == userId)
            .Select(u => u.VipUntil)
            .FirstOrDefaultAsync();

        return VipService.IsVip(vipUntil) ? 2 : 1;
    }

    private static bool CanClaim(DailyRewardState state) =>
        state.LastClaimedAt == null || ToRewardDay(state.LastClaimedAt.Value) < ToRewardDay(DateTime.UtcNow);

    private static DateTime NextClaimAt(DailyRewardState state) =>
        CanClaim(state) ? DateTime.UtcNow : FromRewardDay(ToRewardDay(state.LastClaimedAt!.Value).AddDays(1));

    private static DateTime ToRewardDay(DateTime utcTime) =>
        TimeZoneInfo.ConvertTimeFromUtc(DateTime.SpecifyKind(utcTime, DateTimeKind.Utc), RewardTimeZone).Date;

    private static DateTime FromRewardDay(DateTime localDay) =>
        TimeZoneInfo.ConvertTimeToUtc(DateTime.SpecifyKind(localDay, DateTimeKind.Unspecified), RewardTimeZone);

    private static readonly TimeZoneInfo RewardTimeZone = GetRewardTimeZone();

    private static TimeZoneInfo GetRewardTimeZone()
    {
        try { return TimeZoneInfo.FindSystemTimeZoneById("Europe/Kyiv"); }
        catch
        {
            try { return TimeZoneInfo.FindSystemTimeZoneById("FLE Standard Time"); }
            catch { return TimeZoneInfo.Utc; }
        }
    }

    private static DailyRewardView BuildView(DailyRewardState state, UserStat stat, bool claimed, string? message)
    {
        var canClaim = CanClaim(state);
        return new DailyRewardView(
            stat.Diamons,
            state.CurrentDay,
            canClaim,
            NextClaimAt(state),
            claimed,
            message,
            stat.RainbowNameUnlocked,
            stat.RainbowNameEnabled,
            stat.DiamondEmojiUnlocked,
            stat.DiamondEmojiEnabled,
            Rewards);
    }
}

public record DailyRewardDefinition(int Day, string Title, string Description, int Diamons, string? Cosmetic);

public record DailyRewardView(
    int Diamons,
    int CurrentDay,
    bool CanClaim,
    DateTime NextClaimAt,
    bool Claimed,
    string? Message,
    bool RainbowNameUnlocked,
    bool RainbowNameEnabled,
    bool DiamondEmojiUnlocked,
    bool DiamondEmojiEnabled,
    IReadOnlyList<DailyRewardDefinition> Rewards);
