using System.Globalization;
using System.Net.Http.Json;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using GeneratorGame.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;

namespace GeneratorGame.Services;

public class EnotPaymentService
{
    public const decimal VipPriceRub = 75m;
    public const string ShopId = "8e725c46-695f-4eb4-97cb-42c03e3d0d85";
    public const string WidgetId = "51021f73-ec5c-4178-8a75-4cea5944742c";

    private readonly AppDbContext _db;
    private readonly IHttpClientFactory _httpClientFactory;

    public EnotPaymentService(AppDbContext db, IHttpClientFactory httpClientFactory)
    {
        _db = db;
        _httpClientFactory = httpClientFactory;
    }

    public static string BuildVipWidgetUrl(int userId, string username, string? email)
    {
        var comment = $"VIP-{userId}-{username}";
        var query = new Dictionary<string, string?>
        {
            ["color"] = "white",
            ["size"] = "large",
            ["comment"] = comment,
            ["amount"] = "75",
            ["currency"] = "RUB"
        };

        return QueryString.Create(query).ToUriComponent()
            .Insert(0, $"https://pay.enot.io/widget/{WidgetId}/button");
    }

    public async Task<EnotInvoiceResult> CreateVipInvoiceAsync(int userId, string username, string? email)
    {
        var secret = Environment.GetEnvironmentVariable("ENOT_SECRET_KEY");
        if (string.IsNullOrWhiteSpace(secret))
        {
            return new EnotInvoiceResult(false, null, "ENOT_SECRET_KEY is not configured");
        }

        var orderId = $"vip-{userId}-{DateTimeOffset.UtcNow.ToUnixTimeSeconds()}";
        var payload = new
        {
            amount = VipPriceRub,
            order_id = orderId,
            email = string.IsNullOrWhiteSpace(email) ? null : email,
            currency = "RUB",
            custom_fields = JsonSerializer.Serialize(new { userId, product = "vip_30_days" }),
            comment = $"VIP-{userId}-{username}",
            fail_url = "https://generator-rb.online/vip/fail",
            success_url = "https://generator-rb.online/vip/success",
            hook_url = "https://generator-rb.online/api/enot/webhook",
            shop_id = ShopId,
            expire = 300
        };

        var client = _httpClientFactory.CreateClient();
        using var request = new HttpRequestMessage(HttpMethod.Post, "https://api.enot.io/invoice/create");
        request.Headers.Accept.ParseAdd("application/json");
        request.Headers.Add("x-api-key", secret);
        request.Content = JsonContent.Create(payload);

        using var response = await client.SendAsync(request);
        var body = await response.Content.ReadAsStringAsync();
        if (!response.IsSuccessStatusCode)
        {
            return new EnotInvoiceResult(false, null, $"Enot API error {(int)response.StatusCode}: {body}");
        }

        try
        {
            using var doc = JsonDocument.Parse(body);
            var root = doc.RootElement;
            var statusCheck = !root.TryGetProperty("status_check", out var statusEl) || statusEl.GetBoolean();
            var url = root.GetProperty("data").GetProperty("url").GetString();
            if (!statusCheck || string.IsNullOrWhiteSpace(url))
            {
                return new EnotInvoiceResult(false, null, body);
            }

            return new EnotInvoiceResult(true, url, null);
        }
        catch (Exception ex)
        {
            return new EnotInvoiceResult(false, null, $"Bad Enot response: {ex.Message}");
        }
    }

    public async Task EnsureSchemaAsync()
    {
        if (_db.Database.IsNpgsql())
        {
            await _db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "VipPayments" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "PaymentId" text NOT NULL UNIQUE,
                    "UserId" integer NOT NULL,
                    "Amount" numeric NOT NULL,
                    "Currency" text NOT NULL DEFAULT 'RUB',
                    "Payload" text NOT NULL DEFAULT '',
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT "FK_VipPayments_Users_UserId"
                        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
                );
                """);
            return;
        }

        await _db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "VipPayments" (
                "Id" INTEGER NOT NULL CONSTRAINT "PK_VipPayments" PRIMARY KEY AUTOINCREMENT,
                "PaymentId" TEXT NOT NULL UNIQUE,
                "UserId" INTEGER NOT NULL,
                "Amount" TEXT NOT NULL,
                "Currency" TEXT NOT NULL DEFAULT 'RUB',
                "Payload" TEXT NOT NULL DEFAULT '',
                "CreatedAt" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT "FK_VipPayments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
            );
            """);
    }

    public async Task<EnotWebhookResult> ProcessWebhookAsync(Dictionary<string, string> data, string rawBody)
    {
        var signature = Get(data, "sign", "sign_2", "signature", "hash", "x-api-sha256-signature");
        if (!VerifySignature(data, rawBody, signature))
        {
            return new EnotWebhookResult(false, "Bad signature");
        }

        if (!IsSuccessStatus(data))
        {
            return new EnotWebhookResult(true, "Ignored non-success payment");
        }

        var amount = ParseAmount(Get(data, "amount", "sum", "credited", "credited_amount"));
        if (amount < VipPriceRub)
        {
            return new EnotWebhookResult(false, "Bad amount");
        }

        var currency = Get(data, "currency", "currency_code") ?? "RUB";
        if (!string.Equals(currency, "RUB", StringComparison.OrdinalIgnoreCase))
        {
            return new EnotWebhookResult(false, "Bad currency");
        }

        var comment = Get(data, "comment", "description", "merchant_order_desc", "custom_field");
        var orderId = Get(data, "order_id", "merchant_order_id", "payment_id", "invoice_id", "transaction_id", "id", "intid");
        var userId = ParseUserId(comment)
            ?? ParseUserId(orderId)
            ?? ParseUserIdFromCustomFields(Get(data, "custom_fields", "custom_field"));
        if (userId == null)
        {
            return new EnotWebhookResult(false, "User id not found");
        }

        var paymentId = Get(data, "payment_id", "invoice_id", "transaction_id", "order_id", "merchant_order_id", "id", "intid")
            ?? Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(rawBody)));

        var exists = await PaymentExistsAsync(paymentId);
        if (exists)
        {
            return new EnotWebhookResult(true, "Already processed");
        }

        var user = await _db.Users.FirstOrDefaultAsync(u => u.Id == userId.Value);
        if (user == null)
        {
            return new EnotWebhookResult(false, "User not found");
        }

        var from = user.VipUntil.HasValue && user.VipUntil.Value > DateTime.UtcNow
            ? user.VipUntil.Value
            : DateTime.UtcNow;
        user.VipUntil = from.AddDays(30);

        await InsertPaymentAsync(paymentId, user.Id, amount, currency, rawBody);
        await _db.SaveChangesAsync();

        return new EnotWebhookResult(true, $"VIP activated for user {user.Id}");
    }

    private bool VerifySignature(Dictionary<string, string> data, string rawBody, string? signature)
    {
        var secret = Environment.GetEnvironmentVariable("ENOT_SECRET_KEY");
        var additional = Environment.GetEnvironmentVariable("ENOT_ADDITIONAL_KEY");
        var keys = new[] { additional, secret }
            .Where(k => !string.IsNullOrWhiteSpace(k))
            .Select(k => k!)
            .ToArray();

        if (keys.Length == 0) return false;
        if (string.IsNullOrWhiteSpace(signature)) return false;

        var normalizedSign = NormalizeSign(signature);
        var amount = Get(data, "amount", "sum", "credited", "credited_amount") ?? "";
        var credited = Get(data, "credited", "credited_amount", "amount", "sum") ?? "";
        var orderId = Get(data, "order_id", "merchant_order_id", "payment_id", "invoice_id", "transaction_id", "id", "intid") ?? "";
        var merchantOrderId = Get(data, "merchant_id", "merchant_order_id", "order_id") ?? "";
        var shopId = Get(data, "shop_id", "merchant", "merchant_id", "shop") ?? ShopId;

        foreach (var key in keys)
        {
            var candidates = new[]
            {
                HmacSha256Hex(SortJsonForEnot(rawBody), key),
                HmacSha256Hex(SortJsonForEnot(rawBody, withSpaces: true), key),
                Md5Hex($"{shopId}:{amount}:{key}:{merchantOrderId}"),
                Md5Hex($"{shopId}:{credited}:{key}:{merchantOrderId}"),
                Md5Hex($"{amount}:{shopId}:{key}:{orderId}"),
                Md5Hex($"{shopId}:{amount}:{key}:{orderId}"),
                Md5Hex($"{orderId}:{amount}:{key}"),
                Md5Hex($"{shopId}:{orderId}:{amount}:{key}"),
                Sha256Hex($"{amount}:{shopId}:{key}:{orderId}"),
                Sha256Hex($"{shopId}:{amount}:{key}:{orderId}"),
                HmacSha256Hex(rawBody, key)
            };

            if (candidates.Any(c => FixedEquals(c, normalizedSign))) return true;
        }

        return false;
    }

    private async Task<bool> PaymentExistsAsync(string paymentId)
    {
        var connection = _db.Database.GetDbConnection();
        var shouldClose = connection.State == System.Data.ConnectionState.Closed;
        if (shouldClose) await connection.OpenAsync();

        try
        {
            await using var cmd = connection.CreateCommand();
            cmd.CommandText = _db.Database.IsNpgsql()
                ? """SELECT COUNT(*) FROM "VipPayments" WHERE "PaymentId" = @paymentId"""
                : """SELECT COUNT(*) FROM "VipPayments" WHERE "PaymentId" = $paymentId""";

            var p = cmd.CreateParameter();
            p.ParameterName = _db.Database.IsNpgsql() ? "paymentId" : "$paymentId";
            p.Value = paymentId;
            cmd.Parameters.Add(p);

            var count = Convert.ToInt32(await cmd.ExecuteScalarAsync(), CultureInfo.InvariantCulture);
            return count > 0;
        }
        finally
        {
            if (shouldClose) await connection.CloseAsync();
        }
    }

    private async Task InsertPaymentAsync(string paymentId, int userId, decimal amount, string currency, string payload)
    {
        if (_db.Database.IsNpgsql())
        {
            await _db.Database.ExecuteSqlInterpolatedAsync($"""
                INSERT INTO "VipPayments" ("PaymentId", "UserId", "Amount", "Currency", "Payload", "CreatedAt")
                VALUES ({paymentId}, {userId}, {amount}, {currency}, {payload}, now());
                """);
            return;
        }

        await _db.Database.ExecuteSqlInterpolatedAsync($"""
            INSERT INTO "VipPayments" ("PaymentId", "UserId", "Amount", "Currency", "Payload", "CreatedAt")
            VALUES ({paymentId}, {userId}, {amount.ToString(CultureInfo.InvariantCulture)}, {currency}, {payload}, CURRENT_TIMESTAMP);
            """);
    }

    private static bool IsSuccessStatus(Dictionary<string, string> data)
    {
        var status = (Get(data, "status", "state", "payment_status") ?? "").Trim().ToLowerInvariant();
        if (string.IsNullOrWhiteSpace(status)) return true;
        return status is "success" or "successful" or "paid" or "completed" or "complete" or "succeeded" or "1" or "2";
    }

    private static int? ParseUserId(string? value)
    {
        if (string.IsNullOrWhiteSpace(value)) return null;
        var match = Regex.Match(value, @"VIP-(\d+)", RegexOptions.IgnoreCase);
        return match.Success && int.TryParse(match.Groups[1].Value, out var userId) ? userId : null;
    }

    private static int? ParseUserIdFromCustomFields(string? value)
    {
        if (string.IsNullOrWhiteSpace(value)) return null;
        try
        {
            using var doc = JsonDocument.Parse(value);
            if (TryReadInt(doc.RootElement, "userId", out var id)) return id;
            if (TryReadInt(doc.RootElement, "user_id", out id)) return id;
            if (TryReadInt(doc.RootElement, "user", out id)) return id;
        }
        catch { }

        var parsed = ParseUserId(value);
        if (parsed != null) return parsed;

        if (int.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var directId))
        {
            return directId;
        }

        return null;
    }

    private static bool TryReadInt(JsonElement root, string property, out int value)
    {
        value = 0;
        if (root.ValueKind != JsonValueKind.Object || !root.TryGetProperty(property, out var element)) return false;
        if (element.ValueKind == JsonValueKind.Number && element.TryGetInt32(out value)) return true;
        return element.ValueKind == JsonValueKind.String
            && int.TryParse(element.GetString(), NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
    }

    private static string SortJsonForEnot(string rawBody, bool withSpaces = false)
    {
        try
        {
            using var doc = JsonDocument.Parse(rawBody);
            if (doc.RootElement.ValueKind != JsonValueKind.Object) return rawBody;

            using var stream = new MemoryStream();
            using (var writer = new Utf8JsonWriter(stream, new JsonWriterOptions { Indented = false }))
            {
                writer.WriteStartObject();
                var first = true;
                foreach (var prop in doc.RootElement.EnumerateObject().OrderBy(p => p.Name, StringComparer.Ordinal))
                {
                    if (IsSignatureField(prop.Name)) continue;
                    if (withSpaces)
                    {
                        if (!first) writer.Flush();
                    }

                    prop.WriteTo(writer);
                    first = false;
                }
                writer.WriteEndObject();
            }

            var compact = Encoding.UTF8.GetString(stream.ToArray());
            return withSpaces ? compact.Replace("\":", "\": ").Replace(",", ", ") : compact;
        }
        catch
        {
            return rawBody;
        }
    }

    private static bool IsSignatureField(string name) =>
        string.Equals(name, "sign", StringComparison.OrdinalIgnoreCase) ||
        string.Equals(name, "sign_2", StringComparison.OrdinalIgnoreCase) ||
        string.Equals(name, "signature", StringComparison.OrdinalIgnoreCase) ||
        string.Equals(name, "hash", StringComparison.OrdinalIgnoreCase) ||
        string.Equals(name, "x-api-sha256-signature", StringComparison.OrdinalIgnoreCase);

    private static decimal ParseAmount(string? value)
    {
        if (string.IsNullOrWhiteSpace(value)) return 0;
        value = value.Replace(',', '.');
        return decimal.TryParse(value, NumberStyles.Number, CultureInfo.InvariantCulture, out var amount) ? amount : 0;
    }

    private static string? Get(Dictionary<string, string> data, params string[] keys)
    {
        foreach (var key in keys)
        {
            var match = data.FirstOrDefault(x => string.Equals(x.Key, key, StringComparison.OrdinalIgnoreCase));
            if (!string.IsNullOrWhiteSpace(match.Value)) return match.Value;
        }

        return null;
    }

    private static string NormalizeSign(string signature) =>
        signature.Trim().Replace("sha256=", "", StringComparison.OrdinalIgnoreCase).Replace("sha256:", "", StringComparison.OrdinalIgnoreCase).ToLowerInvariant();

    private static string Md5Hex(string value) =>
        Convert.ToHexString(MD5.HashData(Encoding.UTF8.GetBytes(value))).ToLowerInvariant();

    private static string Sha256Hex(string value) =>
        Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value))).ToLowerInvariant();

    private static string HmacSha256Hex(string value, string key)
    {
        using var hmac = new HMACSHA256(Encoding.UTF8.GetBytes(key));
        return Convert.ToHexString(hmac.ComputeHash(Encoding.UTF8.GetBytes(value))).ToLowerInvariant();
    }

    private static bool FixedEquals(string left, string right)
    {
        var a = Encoding.UTF8.GetBytes(left);
        var b = Encoding.UTF8.GetBytes(right);
        return a.Length == b.Length && CryptographicOperations.FixedTimeEquals(a, b);
    }
}

public record EnotWebhookResult(bool Ok, string Message);
public record EnotInvoiceResult(bool Ok, string? Url, string? Error);
