using GeneratorGame.Data;
using Microsoft.EntityFrameworkCore;

namespace GeneratorGame.Services;

public static class PvpDatabaseInitializer
{
    public static async Task EnsureSchemaAsync(AppDbContext db)
    {
        if (db.Database.IsNpgsql())
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "PvpRatings" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "UserId" integer NOT NULL,
                    "Generator" text NOT NULL,
                    "Points" integer NOT NULL DEFAULT 0,
                    "Wins" integer NOT NULL DEFAULT 0,
                    "Losses" integer NOT NULL DEFAULT 0,
                    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT "FK_PvpRatings_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS "PvpQueueEntries" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "UserId" integer NOT NULL,
                    "Generator" text NOT NULL,
                    "RankIndex" integer NOT NULL DEFAULT 0,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT "FK_PvpQueueEntries_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS "PvpMatches" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Generator" text NOT NULL,
                    "Player1Id" integer NOT NULL,
                    "Player2Id" integer NOT NULL,
                    "Player1Ready" boolean NOT NULL DEFAULT false,
                    "Player2Ready" boolean NOT NULL DEFAULT false,
                    "Player1Wins" integer NOT NULL DEFAULT 0,
                    "Player2Wins" integer NOT NULL DEFAULT 0,
                    "Player1CupDelta" integer NOT NULL DEFAULT 0,
                    "Player2CupDelta" integer NOT NULL DEFAULT 0,
                    "RatingApplied" boolean NOT NULL DEFAULT false,
                    "CurrentRound" integer NOT NULL DEFAULT 1,
                    "Status" text NOT NULL DEFAULT 'waiting_ready',
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT "FK_PvpMatches_Users_Player1Id" FOREIGN KEY ("Player1Id") REFERENCES "Users" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_PvpMatches_Users_Player2Id" FOREIGN KEY ("Player2Id") REFERENCES "Users" ("Id") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS "PvpRounds" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "MatchId" integer NOT NULL,
                    "RoundNumber" integer NOT NULL,
                    "Player1TimeMs" bigint NULL,
                    "Player2TimeMs" bigint NULL,
                    "WinnerUserId" integer NULL,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT "FK_PvpRounds_PvpMatches_MatchId" FOREIGN KEY ("MatchId") REFERENCES "PvpMatches" ("Id") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS "PvpDuelInvites" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "SenderUserId" integer NOT NULL,
                    "TargetUserId" integer NOT NULL,
                    "Generator" text NOT NULL,
                    "Status" text NOT NULL DEFAULT 'pending',
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                    "ExpiresAt" timestamp with time zone NOT NULL,
                    "MatchId" integer NULL,
                    CONSTRAINT "FK_PvpDuelInvites_Users_SenderUserId" FOREIGN KEY ("SenderUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_PvpDuelInvites_Users_TargetUserId" FOREIGN KEY ("TargetUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
                );

                ALTER TABLE "PvpMatches" ADD COLUMN IF NOT EXISTS "RatingApplied" boolean NOT NULL DEFAULT false;
                ALTER TABLE "PvpMatches" ADD COLUMN IF NOT EXISTS "Player1CupDelta" integer NOT NULL DEFAULT 0;
                ALTER TABLE "PvpMatches" ADD COLUMN IF NOT EXISTS "Player2CupDelta" integer NOT NULL DEFAULT 0;

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_PvpRatings_UserId_Generator" ON "PvpRatings" ("UserId", "Generator");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_PvpQueueEntries_UserId_Generator" ON "PvpQueueEntries" ("UserId", "Generator");
                CREATE INDEX IF NOT EXISTS "IX_PvpQueueEntries_Generator_RankIndex_CreatedAt" ON "PvpQueueEntries" ("Generator", "RankIndex", "CreatedAt");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_PvpRounds_MatchId_RoundNumber" ON "PvpRounds" ("MatchId", "RoundNumber");
                CREATE INDEX IF NOT EXISTS "IX_PvpDuelInvites_TargetUserId_Status_ExpiresAt" ON "PvpDuelInvites" ("TargetUserId", "Status", "ExpiresAt");
                """);
            return;
        }

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "PvpRatings" (
                "Id" INTEGER NOT NULL CONSTRAINT "PK_PvpRatings" PRIMARY KEY AUTOINCREMENT,
                "UserId" INTEGER NOT NULL,
                "Generator" TEXT NOT NULL,
                "Points" INTEGER NOT NULL DEFAULT 0,
                "Wins" INTEGER NOT NULL DEFAULT 0,
                "Losses" INTEGER NOT NULL DEFAULT 0,
                "UpdatedAt" TEXT NOT NULL,
                CONSTRAINT "FK_PvpRatings_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS "PvpQueueEntries" (
                "Id" INTEGER NOT NULL CONSTRAINT "PK_PvpQueueEntries" PRIMARY KEY AUTOINCREMENT,
                "UserId" INTEGER NOT NULL,
                "Generator" TEXT NOT NULL,
                "RankIndex" INTEGER NOT NULL DEFAULT 0,
                "CreatedAt" TEXT NOT NULL,
                CONSTRAINT "FK_PvpQueueEntries_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS "PvpMatches" (
                "Id" INTEGER NOT NULL CONSTRAINT "PK_PvpMatches" PRIMARY KEY AUTOINCREMENT,
                "Generator" TEXT NOT NULL,
                "Player1Id" INTEGER NOT NULL,
                "Player2Id" INTEGER NOT NULL,
                "Player1Ready" INTEGER NOT NULL DEFAULT 0,
                "Player2Ready" INTEGER NOT NULL DEFAULT 0,
                "Player1Wins" INTEGER NOT NULL DEFAULT 0,
                "Player2Wins" INTEGER NOT NULL DEFAULT 0,
                "Player1CupDelta" INTEGER NOT NULL DEFAULT 0,
                "Player2CupDelta" INTEGER NOT NULL DEFAULT 0,
                "RatingApplied" INTEGER NOT NULL DEFAULT 0,
                "CurrentRound" INTEGER NOT NULL DEFAULT 1,
                "Status" TEXT NOT NULL DEFAULT 'waiting_ready',
                "CreatedAt" TEXT NOT NULL,
                "UpdatedAt" TEXT NOT NULL,
                CONSTRAINT "FK_PvpMatches_Users_Player1Id" FOREIGN KEY ("Player1Id") REFERENCES "Users" ("Id") ON DELETE CASCADE,
                CONSTRAINT "FK_PvpMatches_Users_Player2Id" FOREIGN KEY ("Player2Id") REFERENCES "Users" ("Id") ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS "PvpRounds" (
                "Id" INTEGER NOT NULL CONSTRAINT "PK_PvpRounds" PRIMARY KEY AUTOINCREMENT,
                "MatchId" INTEGER NOT NULL,
                "RoundNumber" INTEGER NOT NULL,
                "Player1TimeMs" INTEGER NULL,
                "Player2TimeMs" INTEGER NULL,
                "WinnerUserId" INTEGER NULL,
                "CreatedAt" TEXT NOT NULL,
                "UpdatedAt" TEXT NOT NULL,
                CONSTRAINT "FK_PvpRounds_PvpMatches_MatchId" FOREIGN KEY ("MatchId") REFERENCES "PvpMatches" ("Id") ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS "PvpDuelInvites" (
                "Id" INTEGER NOT NULL CONSTRAINT "PK_PvpDuelInvites" PRIMARY KEY AUTOINCREMENT,
                "SenderUserId" INTEGER NOT NULL,
                "TargetUserId" INTEGER NOT NULL,
                "Generator" TEXT NOT NULL,
                "Status" TEXT NOT NULL DEFAULT 'pending',
                "CreatedAt" TEXT NOT NULL,
                "ExpiresAt" TEXT NOT NULL,
                "MatchId" INTEGER NULL,
                CONSTRAINT "FK_PvpDuelInvites_Users_SenderUserId" FOREIGN KEY ("SenderUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
                CONSTRAINT "FK_PvpDuelInvites_Users_TargetUserId" FOREIGN KEY ("TargetUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_PvpRatings_UserId_Generator" ON "PvpRatings" ("UserId", "Generator");
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_PvpQueueEntries_UserId_Generator" ON "PvpQueueEntries" ("UserId", "Generator");
            CREATE INDEX IF NOT EXISTS "IX_PvpQueueEntries_Generator_RankIndex_CreatedAt" ON "PvpQueueEntries" ("Generator", "RankIndex", "CreatedAt");
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_PvpRounds_MatchId_RoundNumber" ON "PvpRounds" ("MatchId", "RoundNumber");
            CREATE INDEX IF NOT EXISTS "IX_PvpDuelInvites_TargetUserId_Status_ExpiresAt" ON "PvpDuelInvites" ("TargetUserId", "Status", "ExpiresAt");
            """);

        await AddColumnIfMissingAsync(db, "PvpMatches", "RatingApplied", """ALTER TABLE "PvpMatches" ADD COLUMN "RatingApplied" INTEGER NOT NULL DEFAULT 0;""");
        await AddColumnIfMissingAsync(db, "PvpMatches", "Player1CupDelta", """ALTER TABLE "PvpMatches" ADD COLUMN "Player1CupDelta" INTEGER NOT NULL DEFAULT 0;""");
        await AddColumnIfMissingAsync(db, "PvpMatches", "Player2CupDelta", """ALTER TABLE "PvpMatches" ADD COLUMN "Player2CupDelta" INTEGER NOT NULL DEFAULT 0;""");
    }

    private static async Task AddColumnIfMissingAsync(AppDbContext db, string table, string column, string sql)
    {
        if (!await ColumnExistsAsync(db, table, column))
        {
            await db.Database.ExecuteSqlRawAsync(sql);
        }
    }

    private static async Task<bool> ColumnExistsAsync(AppDbContext db, string table, string column)
    {
        var connection = db.Database.GetDbConnection();
        var shouldClose = connection.State == System.Data.ConnectionState.Closed;
        if (shouldClose) await connection.OpenAsync();

        try
        {
            await using var command = connection.CreateCommand();
            command.CommandText = $"PRAGMA table_info(\"{table}\");";
            await using var reader = await command.ExecuteReaderAsync();

            while (await reader.ReadAsync())
            {
                if (string.Equals(reader.GetString(1), column, StringComparison.OrdinalIgnoreCase)) return true;
            }

            return false;
        }
        finally
        {
            if (shouldClose) await connection.CloseAsync();
        }
    }
}
